-   id: validate-gitlab-ci
    name: Validate GitLab CI
    description: This hook validates the Gitlab CI yaml file
    entry: validate-gitlab-ci
    language: ruby
    language_version: 2.6.3
    verbose: true
